### ISSUE TITLE
Exception in outbound

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1551]
We often see this in our logs.

````
[DEBUG] [BA776163-54DB-44CA-A871-0C0150B271FD.1] [outbound] running delivered hooks
[DEBUG] [-] [core] [outbound] [outbound::25:207.46.163.215:undefined:300] timeout: 1469552828757
[INFO] [-] [core] [outbound] [outbound::25:207.46.163.215:undefined:300] dispense() clients=0 available=1
[CRIT] [-] [core] Error: read ECONNRESET
[CRIT] [-] [core]     at exports._errnoException (util.js:1008:11)
[CRIT] [-] [core]     at TCP.onread (net.js:563:26)
[NOTICE] [-] [core] Shutting down
````

Any advice?

**Comment by baudehlo** [comment]
It's a failure to add a .on('error') on some socket. I just don't know
where/which the problem would be.

**Comment by smfreegard** [comment]
@baudehlo:   https://github.com/haraka/Haraka/blob/master/outbound.js#L1194 ??

Looks like when the connection is released to the pool, there's no error handler.

**Comment by ricardopolo** [comment]
@baudehlo @smfreegard I can confirm the error happens when the pool is released.

We have the exception 300s after sending the email.
If we change the value of `pool_timeout` to 10s, the exceptions is raised 10s after send the email

**Comment by ricardopolo** [comment]
This also happens when you dont have node clusters


````js
[DEBUG] [-] [core] [outbound] destroyed pool entry for 207.46.163.138:25
[PROTOCOL] [A73E6970-1969-4382-834E-84B10E0A090E.1] [outbound] C: QUIT
[DEBUG] [-] [core] [outbound] [outbound::25:207.46.163.138:undefined:10] removeIdle() all objects removed
[PROTOCOL] [-] [core] [outbound] S: 221 2.0.0 Service closing transmission channel\r\n
[CRIT] [-] [core] Error: read ECONNRESET
[CRIT] [-] [core]     at exports._errnoException (util.js:1008:11)
[CRIT] [-] [core]     at TCP.onread (net.js:563:26)
[NOTICE] [-] [core] Shutting down
````

**Comment by baudehlo** [comment]
Fixed by #1561

**Comment by acharkizakaria** [comment]
Still getting the same issue using Haraka version 2.8.13 :

[INFO] [-] [core] [outbound] [outbound::25:104.44.194.232:undefined:50] dispense() clients=0 available=3
[PROTOCOL] [32F2A1BC-3998-4966-9BEE-87D23AFCECA9.1.1] [outbound] C: RSET
[CRIT] [-] [core] Error: read ECONNRESET
[CRIT] [-] [core]     at exports._errnoException (util.js:1034:11)
[CRIT] [-] [core]     at TCP.onread (net.js:580:26)
[NOTICE] [-] [core] Shutting down

Any glue?

**Comment by baudehlo** [comment]
Currently the only solution is to downgrade to 2.8.4. I just haven't had time to look at it yet. Or find a fix yourself and issue a pull request.

**Comment by acharkizakaria** [comment]
Ok, thanks for your response, I think that was already noted and I don't have to open a new issue is that right?

**Comment by smfreegard** [comment]
Yes - just grab the outbound.js file from 2.8.4 and replace your local copy with it.   It will then use non-pooled connections which is where the problem seems to lay.
